extends SceneTree

func _init() -> void:
	var art := ArtCatalog.new()
	assert(art.bun_frames.size() == 36)
	for texture: AtlasTexture in art.bun_frames:
		var image: Image = texture.atlas.get_image().get_region(Rect2i(texture.region))
		var bounds: Rect2i = image.get_used_rect()
		assert(bounds.size.x > 60 and bounds.size.y > 35)
		assert(bounds.position.x >= 12 and bounds.position.y >= 12)
		assert(bounds.end.x <= 244 and bounds.end.y <= 220)
	var run := RunController.new()
	run.new_run(81)
	var animator := UnitAnimator.new()
	animator.bind(run, BoardProjection.new())
	run.start()
	animator.advance(0, [])
	assert(run.board.place("bun", 2, 1, false) == "")
	var unit: Dictionary = run.state.units[-1]
	assert(animator.bun_frame(unit) == Vector2i(0, 1))
	animator.advance(0.4, [])
	assert(animator.bun_frame(unit).y == 0)
	animator.act(unit.uid)
	assert(animator.bun_frame(unit) == Vector2i(0, 2))
	run.combat.damage_unit(unit, 1)
	assert(animator.bun_frame(unit) == Vector2i(0, 3))
	var frozen: Vector2i = animator.bun_frame(unit)
	animator.advance(0, [])
	assert(animator.bun_frame(unit) == frozen)
	animator.advance(0.31, [])
	assert(animator.bun_frame(unit).y == 0)
	run.state.phase = "prepare"
	animator.advance(0, [])
	assert(run.board.move(2, 1, 3, 1) == "")
	assert(animator.bun_frame(unit) == Vector2i(0, 5))
	animator.advance(0.4, [])
	assert(animator.bun_frame(unit).y == 0)
	run.start()
	animator.advance(0, [])
	var deaths: int = run.state.metrics.deaths
	run.combat.damage_unit(unit, 100000)
	assert(not run.state.units.has(unit))
	assert(animator.food_corpses.size() == 1)
	var corpse: Dictionary = animator.food_corpses[0]
	assert(animator.bun_frame(corpse) == Vector2i(0, 4))
	run.combat.damage_unit(unit, 100000)
	assert(run.state.metrics.deaths == deaths + 1 and animator.food_corpses.size() == 1)
	animator.advance(0, [])
	assert(corpse.death_age == 0)
	animator.advance(0.62, [])
	assert(animator.bun_frame(corpse) == Vector2i(5, 4))
	assert(animator.bun_pose(corpse, Vector2.ZERO).scale == Vector2.ONE)
	animator.advance(0.11, [])
	assert(animator.food_corpses.is_empty())
	assert(not animator.entries.has(unit.uid))
	# A visual snapshot cannot delay phase transitions or survive a reset.
	animator.food_fall(unit)
	run.state.phase = "prepare"
	animator.advance(0, [])
	assert(animator.food_corpses.is_empty())
	animator.food_fall(unit)
	run.new_run(82)
	animator.bind(run, BoardProjection.new())
	assert(animator.food_corpses.is_empty())
	print("PASS food frames: 36 cells, real hurt/death events, six actions, freeze, death once and cleanup")
	quit()
