extends SceneTree

func _init() -> void:
	var run: RunController = RunController.new()
	run.new_run(7)
	run.start()
	run.board.place("bun",2,0,false)
	run.state.units[0].hp = 100.0
	run.finish_wave()
	assert(run.state.wave == 2 and run.state.phase == "prepare")
	assert(run.state.heat == 50.0 and run.state.units[0].hp == 127.0)
	assert(run.state.recipes.is_empty() and not run.state.choices.is_empty())
	run.finish_wave()
	assert(run.state.heat == 50.0, "wave cannot reset or award heat")
	assert(run.board.move(2,0,1,1) == "")
	assert(run.state.units[0].hp == 127.0 and run.state.units.size() == 1)
	assert(not run.board.has_method("repair"))
	assert(run.state.heat == 50.0 and run.state.units[0].hp == 127.0)
	run.start()
	assert(run.state.cooldowns.is_empty() and run.state.units[0].timer == 0.0)
	run.finish_wave()
	assert(run.state.wave == 3)
	run.start()
	run.finish_wave()
	assert(run.state.wave == 4 and run.state.phase == "prepare")
	print("PASS progression: three waves, heal, move, no paid repair, rewards")
	quit()
