extends SceneTree

func _init() -> void:
	var run := RunController.new()
	run.new_run(81)
	run.start()
	var animator := UnitAnimator.new()
	animator.bind(run, BoardProjection.new())
	var art := ArtCatalog.new()
	for id: String in ArtCatalog.MOUSE_IDS:
		assert(art.mouse_frames[id].size() == 24)
		var sheet: Image = art.mouse_frames[id][0].atlas.get_image()
		assert(sheet.detect_alpha() != Image.ALPHA_NONE)
		for row: int in range(4):
			for col: int in range(6):
				var frame: Image = sheet.get_region(Rect2i(col * 256, row * 256, 256, 256))
				var bounds: Rect2i = frame.get_used_rect()
				assert(bounds.size.x > 60 and bounds.size.y > 40)
				assert(bounds.position.x >= 10 and bounds.position.y >= 10)
				assert(bounds.end.x <= 246 and bounds.end.y <= 222)
		run.combat.spawn(id, 0, run.data.waves[0])
		var enemy: Dictionary = run.combat.enemies[-1]
		animator.advance(0.01, run.combat.enemies)
		enemy.x -= 10
		animator.advance(0.1, run.combat.enemies)
		assert(animator.mouse_frame(enemy).x > 0)
		animator.advance(0.1, run.combat.enemies)
		assert(animator.mouse_frame(enemy) == Vector2i(5, 1))
		animator.act(enemy.uid)
		assert(animator.mouse_frame(enemy) == Vector2i(0, 1))
		run.combat.damage_enemy(enemy, 1, "bun")
		assert(animator.mouse_frame(enemy) == Vector2i(0, 2))
		animator.advance(0.1, run.combat.enemies)
		assert(animator.mouse_frame(enemy).x > 0)
		var frozen: Vector2i = animator.mouse_frame(enemy)
		animator.advance(0, run.combat.enemies)
		assert(animator.mouse_frame(enemy) == frozen)
		var kills: int = run.state.metrics.kills
		run.combat.damage_enemy(enemy, 100000, "bun")
		assert(not run.combat.enemies.has(enemy))
		assert(animator.corpses.size() == 1)
		assert(animator.mouse_frame(animator.corpses[0]) == Vector2i(0, 3))
		run.combat.damage_enemy(enemy, 100000, "bun")
		assert(run.state.metrics.kills == kills + 1 and animator.corpses.size() == 1)
		animator.advance(0, run.combat.enemies)
		assert(animator.corpses[0].death_age == 0)
		animator.advance(0.62, run.combat.enemies)
		assert(animator.mouse_frame(animator.corpses[0]) == Vector2i(5, 3))
		animator.advance(0.11, run.combat.enemies)
		assert(animator.corpses.is_empty())
		assert(not animator.entries.has(enemy.uid))
	run.combat.spawn("gray", 1, run.data.waves[0])
	run.combat.damage_enemy(run.combat.enemies[-1], 100000, "bun")
	run.state.phase = "prepare"
	animator.advance(0, [])
	assert(animator.corpses.is_empty())
	run.new_run(82)
	animator.bind(run, BoardProjection.new())
	assert(animator.entries.is_empty() and animator.corpses.is_empty())
	print("PASS mouse frames: eight IDs, priorities, freeze, death once, expiry and cleanup")
	quit()
